
export const sections = [
  {
    id: 1,
    title: "Introduction",
    content: "🚀 Introducing devifyX – Your Resume, Reimagined for Tech HiringAt devifyX, we're redefining how aspiring developers break into the tech industry. We don’t just help you learn — we help you get hired.Our platform offers real- world coding simulations that produce resume - ready projects — complete with GitHub repositories, live demos, and eye - catching thumbnails.Whether you're building a CRUD dashboard, integrating real APIs, or deploying a full-stack app, every project is scoped to show off your technical depth without wasting time on tutorials.With devifyX, you'll: Build a portfolio that speaks directly to recruiters. Speak confidently in interviews about real project decisions. Launch a resume that’s more than just words — it’s proof of your skills. Join the waitlist today and be ready to launch your tech resume the right way. 🎯 14 days to go.Are you ready ? "
  },
  {
    id: 2,
    title: "Features",
    content: "devifyX is a platform designed to help aspiring developers create strong, job-ready resumes by building real-world, deployable projects. Instead of just learning through basic tutorials, devifyX offers project simulations that mimic real workplace scenarios. These include building full-stack applications with both frontend and backend functionality, integrating real APIs, and deploying them with live demo URLs and GitHub repositories. One of the standout features of devifyX is that every project is designed to act as a resume booster. Each build comes with a structured GitHub repo, a hosted live demo, and a professional project thumbnail — all of which can be added directly to your resume or LinkedIn profile to impress recruiters. The platform is built around smart project design. Projects are scoped in a way that they demonstrate technical depth while remaining achievable within a short time frame. This allows users to build, learn, and deploy quickly without feeling overwhelmed. devifyX also prepares you for interviews. Since the projects are realistic and technically sound, you can confidently discuss your tech stack, design decisions, and implementation strategies in interviews. This bridges the gap between knowing how to code and being able to communicate your work like a professional.Moreover, the platform provides access to a library of practical projects — such as admin dashboards, APIs, design systems, and applications with actual business logic — all far beyond the typical beginner-level tutorials. Each project is formatted to help you stand out, showing not only that you can code but that you can build real, working products.Finally, devifyX makes the entire portfolio-building process seamless by integrating GitHub and live demo hosting. As a bonus, by joining the waitlist, users can stay informed about the launch and receive exclusive project templates straight to their inbox."
  },
  {
    id: 3,
    title: "About",
    content: "devifyX is a career-focused platform built to help developers bridge the gap between learning and getting hired. We empower students and self-taught coders to build real, deployable projects that strengthen their resumes and portfolios. Instead of toy apps and generic tutorials, devifyX provides carefully crafted project simulations that mirror real-world development scenarios. Every project you build comes with a live demo, GitHub repository, and visual assets — making it easy to showcase your skills to recruiters. Our goal is simple: to make your resume speak louder than words. Whether you’re building a CRUD app, working with APIs, or designing full-stack systems, devifyX ensures your work is technically strong, visually appealing, and ready for the job market. We’re not just helping you code — we’re helping you stand out."
  },
  {
    id: 4,
    title: "Conclusion",
    content: "In today’s competitive tech landscape, having a certificate or course completion badge isn’t enough. What truly sets you apart is the ability to demonstrate real, hands-on experience — the kind that shows recruiters you’re ready to contribute from day one. This is exactly what devifyX is built for. We go beyond theory and tutorials.devifyX equips you with the tools, guidance, and environment to build deployable, resume- worthy projects that reflect real - world development scenarios.From designing robust frontend interfaces to building backend systems with real APIs, our project simulations are designed to mimic the exact kind of work developers do in tech companies. Each project you complete through devifyX isn’t just a learning milestone — it becomes a tangible asset for your career.With every build, you get a polished GitHub repository, a live hosted demo, and a professional thumbnail.These assets are not just for show — they are structured to fit directly into your resume, LinkedIn profile, and interview preparation toolkit. But devifyX doesn’t stop at building projects.We focus on helping you communicate your skills effectively — so when you're in front of an interviewer, you’re not just saying “I know React” — you're saying, “I built a full - stack app that uses React on the frontend, Node on the backend, deployed it to Vercel, and handled API integrations and auth.” We are committed to transforming learners into job - ready professionals — and making your transition from “learning to code” to “getting hired for it” smoother, faster, and more impactful. devifyX is more than a platform.It's your launchpad to a real tech career. Get ready to build.Get ready to get noticed.Get ready with devifyX."
}
];